//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Input/playerActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""playerActions"",
    ""maps"": [
        {
            ""name"": ""PCControls"",
            ""id"": ""295b4edf-83b0-464b-aa16-48ba918b6a49"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""c0899982-278f-4681-8d84-eb2819f24dad"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rotate"",
                    ""type"": ""Value"",
                    ""id"": ""402fb209-d9d2-4929-8c94-cf77a11b25d7"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Value"",
                    ""id"": ""2ccc78d6-2ce1-47b6-b9ee-caf4445969cb"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Value"",
                    ""id"": ""5b95ae9e-fd4a-4378-9bb4-ec99f073ae49"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Damage"",
                    ""type"": ""Value"",
                    ""id"": ""da0e1a9b-2d3d-4dd5-b917-f36f00beb44a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Fall"",
                    ""type"": ""Value"",
                    ""id"": ""9a0407b8-20ff-4970-b764-2fafca320817"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""970907bc-fd67-4daf-9043-3d6e97928c38"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eeafc3a8-0ba2-41b4-8af2-21d6da83bff4"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f38086fc-d2e8-42a0-8b4c-f60e97e5280a"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e39db91f-df50-481d-b3d4-5c981bd7f92c"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8d5fdc0d-fcdc-4daa-8ad7-252bd488da40"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Damage"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1c8a9239-b2e8-44d3-b574-075fd82d22c1"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fall"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""eee20da8-e099-42bf-b265-63afe85b4adc"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""3cc1fb2b-f708-461a-8b57-b60ecde91d68"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""f5c56f5c-155b-4bd0-a797-ba1cf1eaab77"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""17a1773d-f7e9-4996-9507-3edf67e1223d"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""c0da0d45-84ed-45e6-bee2-d7850711f51c"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""066206c9-8b89-48eb-a3b7-06c067137b07"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""XRIControls"",
            ""id"": ""0e07839b-2a1a-4048-82aa-0adf8fd520ca"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""2fd72716-d2b1-4cf0-9478-150eeb6eac69"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rotate"",
                    ""type"": ""Value"",
                    ""id"": ""c6301ee9-3c63-4074-a299-5321f27f4062"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""2588be24-8c8b-44a3-831f-af5d4b5984e2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""dad116a2-4df6-4dc4-8e51-4f68347796bd"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2b07ea8a-1776-4c9e-8032-3cd497c5316b"",
                    ""path"": ""<XRController>{LeftHand}/thumbstick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""214f57b8-a274-42a1-be97-a4d7a07bf1f0"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7b4ca211-3437-49df-b5a2-43a5b4962237"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a0b56c9d-36dc-4273-b2c1-bf058126633b"",
                    ""path"": ""<XRController>{LeftHand}/thumbstick/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8c8af763-c1cd-487d-aae1-b248194737d2"",
                    ""path"": ""<XRController>{LeftHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4240f03b-cfc0-47db-8576-e3566a90cb19"",
                    ""path"": ""<XRController>{RightHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""84b230b4-3a19-4da3-bbab-717498da172a"",
                    ""path"": ""<XRController>{RightHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""93683a41-ee5d-426f-92bd-84062c1b69cc"",
                    ""path"": ""<XRController>{LeftHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""PlayerActions"",
            ""bindingGroup"": ""PlayerActions"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<XRController>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // PCControls
        m_PCControls = asset.FindActionMap("PCControls", throwIfNotFound: true);
        m_PCControls_Move = m_PCControls.FindAction("Move", throwIfNotFound: true);
        m_PCControls_Rotate = m_PCControls.FindAction("Rotate", throwIfNotFound: true);
        m_PCControls_Run = m_PCControls.FindAction("Run", throwIfNotFound: true);
        m_PCControls_Jump = m_PCControls.FindAction("Jump", throwIfNotFound: true);
        m_PCControls_Damage = m_PCControls.FindAction("Damage", throwIfNotFound: true);
        m_PCControls_Fall = m_PCControls.FindAction("Fall", throwIfNotFound: true);
        // XRIControls
        m_XRIControls = asset.FindActionMap("XRIControls", throwIfNotFound: true);
        m_XRIControls_Move = m_XRIControls.FindAction("Move", throwIfNotFound: true);
        m_XRIControls_Rotate = m_XRIControls.FindAction("Rotate", throwIfNotFound: true);
        m_XRIControls_Jump = m_XRIControls.FindAction("Jump", throwIfNotFound: true);
        m_XRIControls_Run = m_XRIControls.FindAction("Run", throwIfNotFound: true);
    }

    ~@PlayerActions()
    {
        UnityEngine.Debug.Assert(!m_PCControls.enabled, "This will cause a leak and performance issues, PlayerActions.PCControls.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_XRIControls.enabled, "This will cause a leak and performance issues, PlayerActions.XRIControls.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PCControls
    private readonly InputActionMap m_PCControls;
    private List<IPCControlsActions> m_PCControlsActionsCallbackInterfaces = new List<IPCControlsActions>();
    private readonly InputAction m_PCControls_Move;
    private readonly InputAction m_PCControls_Rotate;
    private readonly InputAction m_PCControls_Run;
    private readonly InputAction m_PCControls_Jump;
    private readonly InputAction m_PCControls_Damage;
    private readonly InputAction m_PCControls_Fall;
    public struct PCControlsActions
    {
        private @PlayerActions m_Wrapper;
        public PCControlsActions(@PlayerActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_PCControls_Move;
        public InputAction @Rotate => m_Wrapper.m_PCControls_Rotate;
        public InputAction @Run => m_Wrapper.m_PCControls_Run;
        public InputAction @Jump => m_Wrapper.m_PCControls_Jump;
        public InputAction @Damage => m_Wrapper.m_PCControls_Damage;
        public InputAction @Fall => m_Wrapper.m_PCControls_Fall;
        public InputActionMap Get() { return m_Wrapper.m_PCControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PCControlsActions set) { return set.Get(); }
        public void AddCallbacks(IPCControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_PCControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PCControlsActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Rotate.started += instance.OnRotate;
            @Rotate.performed += instance.OnRotate;
            @Rotate.canceled += instance.OnRotate;
            @Run.started += instance.OnRun;
            @Run.performed += instance.OnRun;
            @Run.canceled += instance.OnRun;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Damage.started += instance.OnDamage;
            @Damage.performed += instance.OnDamage;
            @Damage.canceled += instance.OnDamage;
            @Fall.started += instance.OnFall;
            @Fall.performed += instance.OnFall;
            @Fall.canceled += instance.OnFall;
        }

        private void UnregisterCallbacks(IPCControlsActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Rotate.started -= instance.OnRotate;
            @Rotate.performed -= instance.OnRotate;
            @Rotate.canceled -= instance.OnRotate;
            @Run.started -= instance.OnRun;
            @Run.performed -= instance.OnRun;
            @Run.canceled -= instance.OnRun;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Damage.started -= instance.OnDamage;
            @Damage.performed -= instance.OnDamage;
            @Damage.canceled -= instance.OnDamage;
            @Fall.started -= instance.OnFall;
            @Fall.performed -= instance.OnFall;
            @Fall.canceled -= instance.OnFall;
        }

        public void RemoveCallbacks(IPCControlsActions instance)
        {
            if (m_Wrapper.m_PCControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPCControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_PCControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PCControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PCControlsActions @PCControls => new PCControlsActions(this);

    // XRIControls
    private readonly InputActionMap m_XRIControls;
    private List<IXRIControlsActions> m_XRIControlsActionsCallbackInterfaces = new List<IXRIControlsActions>();
    private readonly InputAction m_XRIControls_Move;
    private readonly InputAction m_XRIControls_Rotate;
    private readonly InputAction m_XRIControls_Jump;
    private readonly InputAction m_XRIControls_Run;
    public struct XRIControlsActions
    {
        private @PlayerActions m_Wrapper;
        public XRIControlsActions(@PlayerActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_XRIControls_Move;
        public InputAction @Rotate => m_Wrapper.m_XRIControls_Rotate;
        public InputAction @Jump => m_Wrapper.m_XRIControls_Jump;
        public InputAction @Run => m_Wrapper.m_XRIControls_Run;
        public InputActionMap Get() { return m_Wrapper.m_XRIControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(XRIControlsActions set) { return set.Get(); }
        public void AddCallbacks(IXRIControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_XRIControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_XRIControlsActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Rotate.started += instance.OnRotate;
            @Rotate.performed += instance.OnRotate;
            @Rotate.canceled += instance.OnRotate;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Run.started += instance.OnRun;
            @Run.performed += instance.OnRun;
            @Run.canceled += instance.OnRun;
        }

        private void UnregisterCallbacks(IXRIControlsActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Rotate.started -= instance.OnRotate;
            @Rotate.performed -= instance.OnRotate;
            @Rotate.canceled -= instance.OnRotate;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Run.started -= instance.OnRun;
            @Run.performed -= instance.OnRun;
            @Run.canceled -= instance.OnRun;
        }

        public void RemoveCallbacks(IXRIControlsActions instance)
        {
            if (m_Wrapper.m_XRIControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IXRIControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_XRIControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_XRIControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public XRIControlsActions @XRIControls => new XRIControlsActions(this);
    private int m_PlayerActionsSchemeIndex = -1;
    public InputControlScheme PlayerActionsScheme
    {
        get
        {
            if (m_PlayerActionsSchemeIndex == -1) m_PlayerActionsSchemeIndex = asset.FindControlSchemeIndex("PlayerActions");
            return asset.controlSchemes[m_PlayerActionsSchemeIndex];
        }
    }
    public interface IPCControlsActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnRotate(InputAction.CallbackContext context);
        void OnRun(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnDamage(InputAction.CallbackContext context);
        void OnFall(InputAction.CallbackContext context);
    }
    public interface IXRIControlsActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnRotate(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnRun(InputAction.CallbackContext context);
    }
}
